language: node_js
node_js:
  - node
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install
  - npm update

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
services:
  - docker

after_success:
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  #- if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST = "false" ]; then docker push index.docker.io:443/v1/4hwc/enad-frontend:latest; fi
  - docker build -t 4hwc/enad-frontend:latest .
  - docker push 4hwc/enad-frontend:latest

